### ISSUE TITLE
系统登录不上

### ISSUE THREAD

**Issue by hzs2019** [ihandyyy/sportmeetingmanagementsystem#7]
作者你好，我正准备一个运动会的毕设，想参考一下这个项目，但是系统登录不上去

**Comment by ihandyyy** [comment]
留个微信，把错误提示发我看看

**Comment by ihandyyy** [comment]
> 作者你好，我正准备一个运动会的毕设，想参考一下这个项目，但是系统登录不上去

留个微信，把错误提示发我看看

**Comment by hzs2019** [comment]
> > 作者你好，我正准备一个运动会的毕设，想参考一下这个项目，但是系统登录不上去
> 
> 留个微信，把错误提示发我看看

wx：1253788988

**Comment by GXX149674** [comment]
大佬，能给个账号密码吗
